version: 2

sources:

  - name: wellthy
    database: source_database
    schema: source_schema
    description: This is data from the Wellthy production database, extracted via Stitch.
    freshness: # default freshness
      warn_after: {count: 24, period: hour}
    loaded_at_field: _SDC_RECEIVED_AT
    tables:
      - name: project
        description: A Table that contains all current project related details.
        columns:
          - name: id
            description: Primary Key of the activity project table.
            tests:
              - not_null
              - unique
          - name: type
          - name: status
          - name: first_active
          - name: created
          - name: modified
          - name: creator_id
            description : The ID of a project's creator.
            tests:
              - not_null:
                  severity: warn

      - name: historical_project
        description: History table for projects
        columns:
          - name: history_id
            description: Primary key of the history project table.
            tests:
              - not_null
              - unique
          - name: id
            description: The project ID.
          - name: type
          - name: status
          - name: first_active
          - name: created
          - name: history_date
            description: The date a project was modified.
          - name: history_user_id
            description: The ID of the person that made a change to the project.
            tests:
             - not_null

      - name: task 
        description: A table that contains a project's task information.
        columns:
          - name: id
            description: The id column is the primary key of the task table.
            tests: 
              - not_null
              - unique
          - name: created
          - name: modified
          - name: status
          - name: title
          - name: due
          - name: project_id
            description: The project ID associated with a task.
            tests: 
              - not_null:
                  where: '_sdc_deleted_at is null'
                  severity: warn
              - relationships:
                  to: source ('wellthy' , 'project')
                  field: id

      - name: historical_task
        description: A history table for tasks
        columns:
          - name: history_id
            description: Primary key of the history task table.
            tests:
              - not_null
              - unique
          - name: id
          - name: created
          - name: status
          - name: title
          - name: due
          - name: history_date
            description: The date a task was modified.
          - name: history_user_id
            description: The ID of the person that made a change to the task.
            tests:
             - not_null